const mockData = [
    {
      id: 1,
      reporter: "John Doe",
      category: "Bug",
      description: "App crashes on startup",
      location: "New York",
      upvotes: 5,
      severity: "High",
    },
    {
      id: 2,
      reporter: "Jane Smith",
      category: "Feature Request",
      description: "Add dark mode",
      location: "London",
      upvotes: 10,
      severity: "Medium",
    },
    {
      id: 3,
      reporter: "Alice Johnson",
      category: "UI Issue",
      description: "Button misaligned on profile page",
      location: "San Francisco",
      upvotes: 3,
      severity: "Low",
    },
    {
      id: 4,
      reporter: "Bob Brown",
      category: "Bug",
      description: "Unable to reset password",
      location: "Chicago",
      upvotes: 7,
      severity: "High",
    },
    {
      id: 5,
      reporter: "Charlie Davis",
      category: "Feature Request",
      description: "Enable two-factor authentication",
      location: "Seattle",
      upvotes: 15,
      severity: "Medium",
    },
    {
      id: 6,
      reporter: "Eve Thompson",
      category: "Performance",
      description: "App takes too long to load",
      location: "Austin",
      upvotes: 9,
      severity: "High",
    },
    {
      id: 7,
      reporter: "Franklin White",
      category: "Bug",
      description: "Notifications not working",
      location: "Boston",
      upvotes: 4,
      severity: "Medium",
    },
    {
      id: 8,
      reporter: "Grace Hall",
      category: "Security",
      description: "Data leakage vulnerability detected",
      location: "Denver",
      upvotes: 20,
      severity: "Critical",
    },
    {
      id: 9,
      reporter: "Hank Wilson",
      category: "Feature Request",
      description: "Add voice commands for navigation",
      location: "Miami",
      upvotes: 12,
      severity: "Low",
    },
    {
      id: 10,
      reporter: "Ivy Martinez",
      category: "Bug",
      description: "Search function not returning results",
      location: "Los Angeles",
      upvotes: 6,
      severity: "Medium",
    },
    {
      id: 11,
      reporter: "Jack Peterson",
      category: "Performance",
      description: "Frequent app freezes",
      location: "San Diego",
      upvotes: 8,
      severity: "High",
    },
    {
      id: 12,
      reporter: "Karen Lee",
      category: "UI Issue",
      description: "Text overlap in settings page",
      location: "Philadelphia",
      upvotes: 5,
      severity: "Low",
    },
    {
      id: 13,
      reporter: "Liam Turner",
      category: "Security",
      description: "Weak encryption on login page",
      location: "Houston",
      upvotes: 14,
      severity: "Critical",
    },
    {
      id: 14,
      reporter: "Mia Walker",
      category: "Bug",
      description: "File uploads fail at 50% progress",
      location: "Phoenix",
      upvotes: 9,
      severity: "High",
    },
    {
      id: 15,
      reporter: "Noah Adams",
      category: "Feature Request",
      description: "Offline mode support",
      location: "Dallas",
      upvotes: 16,
      severity: "Medium",
    },
    {
      id: 16,
      reporter: "Olivia Roberts",
      category: "Performance",
      description: "Memory leak causing high RAM usage",
      location: "San Jose",
      upvotes: 11,
      severity: "High",
    },
    {
      id: 17,
      reporter: "Paul King",
      category: "Bug",
      description: "Audio not playing in background mode",
      location: "Atlanta",
      upvotes: 7,
      severity: "Medium",
    },
    {
      id: 18,
      reporter: "Quinn Carter",
      category: "Security",
      description: "Session timeout too short",
      location: "Portland",
      upvotes: 6,
      severity: "Low",
    },
    {
      id: 19,
      reporter: "Ryan Scott",
      category: "Feature Request",
      description: "More customization options for profiles",
      location: "Las Vegas",
      upvotes: 13,
      severity: "Low",
    },
    {
      id: 20,
      reporter: "Sophia Green",
      category: "Bug",
      description: "Push notifications delayed",
      location: "Washington D.C.",
      upvotes: 8,
      severity: "Medium",
    },
  ];
  
  export default mockData;
  